# Generated by Django 5.1.4 on 2025-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(verbose_name="Malumot kiriting")),
            ],
            options={
                "verbose_name": "Bot haqida Malumot",
                "verbose_name_plural": "Bot haqida Malumot",
                "db_table": "about",
            },
        ),
        migrations.CreateModel(
            name="AdvertisingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Reklama nomi")),
                (
                    "video",
                    models.FileField(
                        upload_to="ads_video/",
                        verbose_name="Reklama videosini kiriting",
                    ),
                ),
                (
                    "video_link",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Video Linki",
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(
                        default=True, help_text="Reklama faoligini belgilang"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Reklama",
                "verbose_name_plural": "Reklama",
                "db_table": "Advertising",
                "managed": True,
            },
        ),
    ]
