# Generated by Django 5.1.4 on 2025-01-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("delivery", "Dostavka"), ("pickup", "Olib Ketish")],
                        default="delivery",
                        max_length=50,
                        verbose_name="Yetkazib berish turi",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Naqt pul")],
                        default="cash",
                        max_length=50,
                        verbose_name="To'lov turi",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ism")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Telefon raqam"),
                ),
                ("address", models.TextField(verbose_name="Manzil")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.usermodel",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Miqdor"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narx"
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.colormodel",
                        verbose_name="Mahsulot rangi",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productmodel",
                        verbose_name="Mahsulot",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.sizemodel",
                        verbose_name="Mahsulot o'lchami",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="order.ordermodel",
                        verbose_name="Buyurtma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma mahsuloti",
                "verbose_name_plural": "Buyurtma mahsulotlari",
                "db_table": "order_item",
            },
        ),
    ]
