# Generated by Django 5.1.4 on 2025-01-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="counties",
            field=models.CharField(default=1, max_length=100, verbose_name="Viloyat"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="payment_method",
            field=models.CharField(
                choices=[("Naqt pul", "Naqt pul")],
                default="cash",
                max_length=50,
                verbose_name="To'lov turi",
            ),
        ),
    ]
