# Generated by Django 5.1.4 on 2025-01-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_ordermodel_counties_alter_ordermodel_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="counties",
        ),
    ]
