# Generated by Django 5.1.4 on 2025-01-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_ordermodel_counties"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="counties",
            field=models.CharField(default=1, max_length=100, verbose_name="Viloyat"),
            preserve_default=False,
        ),
    ]
