# Generated by Django 5.1.4 on 2025-01-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_ordermodel_counties"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="counties",
            new_name="country",
        ),
    ]
