# Generated by Django 5.1.4 on 2025-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_rename_counties_ordermodel_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="To'langanmi?"),
        ),
    ]
