# Generated by Django 5.1.4 on 2025-07-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_ordermodel_is_paid"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Umumiy summa"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="To'langanmi?"),
                ),
                (
                    "payme_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Payme tranzaksiya ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "orders",
                    models.ManyToManyField(
                        related_name="payment_sessions",
                        to="order.ordermodel",
                        verbose_name="Buyurtmalar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.usermodel",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov sessiyasi",
                "verbose_name_plural": "To'lov sessiyalari",
                "db_table": "payment_session",
            },
        ),
    ]
